### ISSUE TITLE
Error when retrieving suggestions

### ISSUE THREAD

**Issue by Ra0R** [canopas/strapi-plugin-tagsinput#8]
I have to collection types:
Variation Tags (`/variation-tags/`) and Variations (`/variation`).

I added the Custom Field -  Tag to the Variations with following config:
![image](https://github.com/canopas/strapi-plugin-tagsinput/assets/22443382/2894a25e-8245-4cc4-b310-9a14a70c9a6e)

Note: I removed the "/v1/" from the API-Path. Is this necessary?

Now everytime I enter a letter I get the following error in console:

![image](https://github.com/canopas/strapi-plugin-tagsinput/assets/22443382/1e035bcd-33aa-44ae-bdfd-a37396512330)

**Comment by cp-sumi-k** [comment]
@Ra0R, Please first check the API response in the browser or Postman. 

Make sure you are adding correct API path and the response should be in proper format something like below, 

```
  [
      { name: "tag1" },
      { name: "tag2" }
  ]
```

**Comment by Ra0R** [comment]
@cp-sumi-k 
The response is in this style:


https://docs.strapi.io/dev-docs/api/rest/sort-pagination

Divided into `data` and `meta`. Btw it should be possible to just use the entity service directly, like so (instead of querying the Rest-API):

https://docs.strapi.io/dev-docs/api/entity-service/populate

What do you think about that?

**Comment by gwu929** [comment]
I have same issue.
The strapi API response format is different, it is like below, i.e. "Name": "Swiss" is nested in data[index].attributes.Name
just wondering if you could enhance the plugin so that it works with Strapi API response out of box.
{
"data": [
{
"id": 1,
"attributes": {
"Name": "Swiss"
}
},
{
"id": 2,
"attributes": {
"Name": "german"
}
}
],
"meta": {
"pagination": {
"page": 1,
"pageSize": 25,
"pageCount": 1,
"total": 2
}
}
}

**Comment by cp-sumi-k** [comment]
Fixed in #10 PR
